### PR TITLE
Add sharpness, contrast, brightness and saturation control

### PR DESCRIPTION
**Pull request by TechnoDezi**
When dealing with lower light situations as well as IR lit night vision then it becomes very important to be able to set the sharpness, contrast, brightness and saturation.

### CODE REVIEW

**Comment by john-doherty** [comment]
Nice work @TechnoDezi, would you mind updating the readme and I'll get this merged/published.

**Comment by TechnoDezi** [comment]
Hey

Thanks. It's already been updated on the second commit. Is there anything else you need on the readme?

**Comment by TechnoDezi** [comment]
I realized now that commander used for the commands doesn't like the double digits, and use them as individual commands. I will change it and push a new commit.

**Comment by TechnoDezi** [comment]
Please review and let me know if there is anything else I can add or do on it. It's a super project and would be nice to extend on it.

**Comment by john-doherty** [comment]
Looks great. Thank you

**Pull request merged**
